modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_eureka"
version = "${version}"
displayName = "VS Eureka Mod"
authors = ["Tri0de", "ewoudje", "VS2 Discord Artists"]
description = '''
Basically Archimedes Ships, but with VS2 as the backend!
'''
logoFile = "icon.png"

[[dependencies.vs_eureka]]
modId = "forge"
mandatory = false
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "valkyrienskies"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "architectury"
mandatory = false
versionRange = "[1.31.61,)"
ordering = "AFTER"
side = "BOTH"