modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_eureka"
version = "${version}"
displayName = "VS Eureka Mod"
authors = ["Tri0de", "ewoudje", "VS2 Discord Artists"]
description = '''
Basically Archimedes Ships, but with VS2 as the backend!
'''
logoFile = "icon.png"

[[dependencies.vs_eureka]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"